name: flake8 scan

on:
  # Allows you to run this workflow when push
  #push:
  #  branches:
  #  tags:
  # Allows you to run this workflow when pull_request
  #pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  main:
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          python: 3.9
          toxenv: flake8
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - run: python -m pip install flake8
    - run: python -m pip install flake8-sarif
    - name: Scan
      continue-on-error: true
      run: flake8 src --format=sarif --output-file=results.sarif
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        path: results.sarif
    - name: Upload SARIF to GitHub
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: results.sarif
