name: scan

on:
  push:
    branches:
    tags:
  pull_request:

jobs:
  main:
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          python: 3.9
          toxenv: flake8
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    #- run: python -mpip install --upgrade setuptools pip tox virtualenv
    - run: python -m pip install flake8
    - run: python -m pip install flake8-sarif
    - run: flake8 . --format=sarif > results.sarif
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        path: results.sarif

    - name: Upload SARIF to GitHub
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: results.sarif

